language: java
install: true
os: linux
dist: trusty
jdk: oraclejdk8

before_script:
  - ./gradlew assemble
script:
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)